export default {
  config: {
    locales: [
       'en',
       'tr'

    ],
    translations: {
      tr: {
        "Auth.components.Oops.text": "Hesabınız askıya alındı.",
        "Auth.components.Oops.text.admin": "Bu bir hataysa, lütfen yöneticinize başvurun.",
        "Auth.components.Oops.title": "Hay ...",
        "Auth.form.button.go-home": "EVE GERI DöN",
        "Auth.form.button.login.providers.error": "Sizi seçilen sağlayıcıdan bağlamayız.",
        "Auth.form.button.login.strapi": "Strapi aracılığıyla oturum aç",
        "Auth.form.button.password-recovery": "Parola Kurtarma",
        "Auth.form.confirmPassword.label": "Doğrulama Parolası",
        "Auth.form.currentPassword.label": "Geçerli Parola", 
        "Auth.form.firstname.label": "Adı",
        "Auth.form.firstname.placeholder": "örneğin Kai",
        "Auth.form.lastname.label": "Soyadı",
        "Auth.form.lastname.placeholder": "Örn.",
        "Auth.form.password.hide-password": "Parolayı gizle",
        "Auth.form.password.hint": "En az 8 karakter, 1 büyük harf, 1 küçük harf ve 1 sayı olmalıdır",
        "Auth.form.password.show-password": "Parolayı göster",
        "Auth.form.register.subtitle": "Kimlik bilgileri yalnızca Strapi içinde kimlik doğrulaması yapmak için kullanılır. Kaydedilen tüm veriler veritabanınızda saklanacaktır.",
        "Auth.form.welcome.subtitle": "Strapi hesabınızda oturum açın",
        "Auth.form.welcome.title": "Strapi 'ye hoş geldiniz!",
        "Auth.link.signin": "Oturum açın",
        "Auth.link.signin.account": "Hesabınız zaten var mı?",
        "Auth.login.sso.divider": "Ya da oturum açma",
        "Auth.login.sso.loading": "Sağlayıcılar yükleniyor ...",
        "Auth.login.sso.subtitle": "SSO aracılığıyla hesabınızda oturum açın",
        "Auth.reset-password.title": "Parolayı sıfırla",
        "Content Type Builder": "İçerik Tipleri Oluşturucu",
        "Documentation": "Belgeler",
        "Media Library": "Ortam Kitaplığı",
        "Roles & Permissions": "Roller ve İzinler",
        "Roles.ListPage.notification.delete-all-not-allowed": "Bazı roller, kullanıcılarla ilişkilendirildiği için silinemedi",
        "Roles.ListPage.notification.delete-not-allowed": "Bir rol, kullanıcılarla ilişkilendirildiyse silinemez",
        "Roles.RoleRow.select-all": "Toplu işlemler için { name } seç",
        "Roles.RoleRow.user-count": "{ number, plural, = 0 { # user } one { # user } other { # users } }",
        "Roles.components.List.empty.withSearch": "Aramayla ilgili herhangi bir rol yok ({ search }) ...",
        "Settings.PageTitle": "Ayarlar-{ name }",
        "Settings.apiTokens.addFirstToken": "İlk API Simg'inizi ekleyin",
        "Settings.apiTokens.addNewToken": "Yeni API Belirteci Ekle",
        "Settings.apiTokens.copy.editMessage": "Güvenlik nedenlerinden dolayı yalnızca bir kez belirtecinizi görebilirsiniz.",
        "Settings.apiTokens.copy.editTitle": "Bu belirteç artık erişilebilir değil.",
        "Settings.apiTokens.copy.lastWarning": "Bu simgeyi kopyaladığınızdan emin olun, bir daha göremeyeceksiniz!",
        "Settings.apiTokens.create": "Yeni API Belirteci Yarat",
        "Settings.apiTokens.description": "API ' yı tüketebilmek için oluşturulan simgelerin listesi",
        "Settings.apiTokens.emptyStateLayout": "Henüz bir içeriğiniz yok ...",
        "Settings.apiTokens.notification.copied": "Simge panoya kopyalandı.",
        "Settings.apiTokens.title": "API Simgeleri",
        "Settings.apiTokens.types.full-access": "Tam erişim",
        "Settings.apiTokens.types.read-only": "Salt okunur",
        "Settings.application.description": "Yönetim panosunun genel bilgileri",
        "Settings.application.edition-title": "geçerli plan",
        "Settings.application.get-help": "Yardım al",
        "Settings.application.link-pricing": "Tüm fiyatlandırma planlarını görün",
        "Settings.application.link-upgrade": "Yönetici panonuzun büyütülmesi",
        "Settings.application.node-version": "düğüm sürümü",
        "Settings.application.strapi-version": "strapi sürümü",
        "Settings.application.strapiVersion": "strapi sürümü",
        "Settings.application.title": "Genel Bakış",
        "Settings.permissions": "Denetim panosu",
        "Settings.permissions.category": "{ category } için izin ayarları",
        "Settings.permissions.category.plugins": "{ category } eklentisine ilişkin izin ayarları",
        "Settings.permissions.conditions.anytime": "Her Zaman",
        "Settings.permissions.conditions.apply": "Uygula",
        "Settings.permissions.conditions.can": "Can",
        "Settings.permissions.conditions.define-conditions": "Koşulları tanımla",
        "Settings.permissions.conditions.links": "Bağlantılar",
        "Settings.permissions.conditions.no-actions": "Önce koşulları tanımlamadan önce işlemleri (yaratma, okuma, güncelleme, ...) seçmeniz ilk kez gerekir.",
        "Settings.permissions.conditions.none-selected": "Her Zaman",
        "Settings.permissions.conditions.or": "YA DA",
        "Settings.permissions.conditions.when": "Zamanı",
        "Settings.permissions.select-all-by-permission": "Tüm { label } izinlerini seç",
        "Settings.permissions.select-by-permission": "{ label } iznini seçin",
        "Settings.permissions.users.create": "Yeni kullanıcıyı davet et",
        "Settings.permissions.users.form.email": "Eposta",
        "Settings.permissions.users.form.firstname": "Adı",
        "Settings.permissions.users.form.lastname": "Soyadı",
        "Settings.permissions.users.form.sso": "SSO ile bağlan",
        "Settings.permissions.users.form.sso.description": "(ON) etkinleştirildiğinde, kullanıcılar SSO (SSO) aracılığıyla oturum açabilirler",
        "Settings.permissions.users.listview.header.subtitle": "Strapi yönetici panosuna erişimi olan tüm kullanıcılar",
        "Settings.permissions.users.tabs.label": "Sekmeler İzinleri",
        "Settings.profile.form.notify.data.loaded": "Profil verileriniz yüklendi",
        "Settings.profile.form.section.experience.clear.select": "Seçilen arabirim dilini temizle",
        "Settings.profile.form.section.experience.here": "burayı tıklatın",
        "Settings.profile.form.section.experience.interfaceLanguage": "Arabirim dili",
        "Settings.profile.form.section.experience.interfaceLanguage.hint": "Bu, yalnızca kendi arabiriminizi seçilen dilde görüntüler.",
        "Settings.profile.form.section.experience.interfaceLanguageHelp": "Tercih değişiklikleri yalnızca sizin için geçerli olur. Daha fazla bilgi için bkz. { burada }.",
        "Settings.profile.form.section.experience.mode.label": "Arabirim kipi",
        "Settings.profile.form.section.experience.mode.hint": "Arabiriminizi seçilen kipte görüntüler.",
        "Settings.profile.form.section.experience.mode.option-label": "{ name } kipi",
        "Settings.profile.form.section.experience.title": "Deneyim",
        "Settings.profile.form.section.helmet.title": "Kullanıcı tanıtımı",
        "Settings.profile.form.section.profile.page.title": "Profil sayfası",
        "Settings.roles.create.description": "Role verilen hakları tanımlayın",
        "Settings.roles.create.title": "Rol yarat",
        "Settings.roles.created": "Rol yaratıldı",
        "Settings.roles.edit.title": "Rolü düzenle",
        "Settings.roles.form.button.users-with-role": "{ number, plural, = 0 { # users } one { # user } other { # users } } bu rolle",
        "Settings.roles.form.created": "Oluşturuldu",
        "Settings.roles.form.description": "Rolün adı ve açıklaması",
        "Settings.roles.form.permission.property-label": "{ label } izinleri",
        "Settings.roles.form.permissions.attributesPermissions": "Alan izinleri",
        "Settings.roles.form.permissions.create": "Oluştur",
        "Settings.roles.form.permissions.delete": "Sil",
        "Settings.roles.form.permissions.publish": "Yayınla",
        "Settings.roles.form.permissions.read": "Oku",
        "Settings.roles.form.permissions.update": "Güncelleştir",
        "Settings.roles.list.button.add": "Yeni rol ekle",
        "Settings.roles.list.description": "Rollerin listesi",
        "Settings.roles.title.singular": "rol",
        "Settings.sso.description": "Single Sign-On (Tek Oturum Açma) özelliğinin ayarlarını yapılandırın.",
        "Settings.sso.form.defaultRole.description": "Kimliği doğrulanmış yeni kullanıcıyı seçilen role ekleyecektir.",
        "Settings.sso.form.defaultRole.description-not-allowed": "Yönetici rollerini okuma iznine sahip olmasınız",
        "Settings.sso.form.defaultRole.label": "Varsayılan rol",
        "Settings.sso.form.registration.description": "Herhangi bir hesap yoksa, SSO oturum açısında yeni kullanıcı oluştur",
        "Settings.sso.form.registration.label": "Otomatik kayıt",
        "Settings.sso.title": "Tekli Oturum Açma",
        "Settings.webhooks.events.update": "Güncelleştir",
        "Settings.webhooks.headers.remove": "{ number } üstbilgi satırını kaldır",
        "Settings.webhooks.list.th.actions": "işlemler",
        "Settings.webhooks.list.th.status": "durum",
        "Settings.webhooks.to.delete": "{ webhookksToDeleteLength, plural, one { # asset } diğer { # varlıklar } } seçildi",
        "Usecase.back-end": "Arka uç geliştiricisi",
        "Usecase.button.skip": "Bu soruyu atla",
        "Usecase.content-creator": "İçerik Yaratan",
        "Usecase.front-end": "Ön uç geliştirici",
        "Usecase.full-stack": "Tam yığın geliştirici",
        "Usecase.input.work-type": "Ne tür bir iş yapıyorsun?",
        "Usecase.notification.success.project-created": "Proje başarıyla yaratıldı",
        "Usecase.other": "Diğer",
        "Usecase.title": "Bize biraz kendinden bahset.",
        "Users.components.List.empty": "Kullanıcı yok ...",
        "Users.components.List.empty.withFilters": "Uygulanan süzgeçlere sahip bir kullanıcı yok ...",
        "Users.components.List.empty.withSearch": "Aramayla ilgili kullanıcı yok ({ search }) ...",
        "admin.pages.MarketPlacePage.helmet": "Pazar Yeri-Eklentiler",
        "admin.pages.MarketPlacePage.offline.title": "Çevrimdışısınız",
        "admin.pages.MarketPlacePage.offline.subtitle": "Strapi Market olanağına erişmek için İnternet 'e bağlanmanız gerekir.",
        "admin.pages.MarketPlacePage.plugin.copy": "Kuruluş komutunu kopyala",
        "admin.pages.MarketPlacePage.plugin.copy.success": "Yükleme komutu uçbiriminize yapıştırılmaya hazır",
        "admin.pages.MarketPlacePage.plugin.info": "Ek bilgi",
        "admin.pages.MarketPlacePage.plugin.info.label": "{ pluginName } hakkında daha fazla bilgi edinin",
        "admin.pages.MarketPlacePage.plugin.info.text": "Ek bilgi",
        "admin.pages.MarketPlacePage.plugin.installed": "Kurulu",
        "admin.pages.MarketPlacePage.plugin.tooltip.madeByStrapi": "Strapi tarafından yapıldı",
        "admin.pages.MarketPlacePage.plugin.tooltip.verified": "Plugin, Strapi tarafından doğrulandı",
        "admin.pages.MarketPlacePage.search.clear": "Eklenti aramasını temizle",
        "admin.pages.MarketPlacePage.search.empty": "\"{ target }\" için sonuç yok",
        "admin.pages.MarketPlacePage.search.placeholder": "Eklenti ara",
        "admin.pages.MarketPlacePage.submit.plugin.link": "Eklentinizi gönderin",
        "admin.pages.MarketPlacePage.subtitle": "Strapi dışında daha fazla bilgi al",
        "admin.pages.MarketPlacePage.missingPlugin.title": "Eklenti eksik mi?",
        "admin.pages.MarketPlacePage.missingPlugin.description": "Bize hangi eklentinin aradığınızı söyleyin ve topluluk eklentisi geliştiricilerimizin ilham arayışlarında olduklarını bilmelerine izin verin!",
        "anErrorOccurred": "Woops! Bir şeyler ters gitti. Lütfen, tekrar dene.",
        "app.component.CopyToClipboard.label": "Panoya kopyala",
        "app.component.search.label": "{ target } için arama yapın",
        "app.component.table.duplicate": "Yinelenen { target }",
        "app.component.table.edit": "{ target } Öğesini Düzenle",
        "app.component.table.select.one-entry": "{ target } seçeneğini belirleyin",
        "app.components.BlockLink.blog": "Web Günlüğü",
        "app.components.BlockLink.blog.content": "Strapi ve ekosistem hakkındaki en son haberleri okuyun.",
        "app.components.BlockLink.code.content": "Gerçek projeleri test ederek öğrenin, topluluğu geliştirmiş olun.",
        "app.components.BlockLink.documentation.content": "Temel kavramları, kılavuzları ve yönergeleri keşfedin.",
        "app.components.BlockLink.tutorial": "Eğitmenler",
        "app.components.BlockLink.tutorial.content": "Strapi olanağını kullanmak ve uyarlamak için adım adım yönergeleri izleyin.",
        "app.components.Button.confirm": "Doğrula",
        "app.components.ConfirmDialog.title": "Onay",
        "app.components.EmptyStateLayout.content-document": "İçerik bulunamadı",
        "app.components.EmptyStateLayout.content-permissions": "Bu içeriğe erişmek için gereken izinlere sahip değil",
        "app.components.GuidedTour.CM.create.content": "<p>Content Manager 'da buradaki tüm içeriği oluşturun ve yönetin.</p><p>Ex: Web günlüğü web sitesini daha ayrıntılı bir şekilde ele almak, bir makale yazabilir, kaydedebilir ve yayınlayabilir.</p><p>💡 Hızlı İpucu-Oluşturdığınız içerik üzerinde yayınlama yapmayı unutmayın.</p>",
        "app.components.GuidedTour.CM.create.title": "⚡️ İçerik yarat",
        "app.components.GuidedTour.CM.success.content": "<p>Şahane, son bir adım daha!</p><b>🚀 İşteki içeriği görün</b>",
        "app.components.GuidedTour.CM.success.cta.title": "API ' yi Sına",
        "app.components.GuidedTour.CM.success.title": "Adım 2: Tamamlanan ✅",
        "app.components.GuidedTour.CTB.create.content": "<p>Kaynak grubu tipleri çeşitli girdileri yönetmenize yardımcı olur, Tek tipler yalnızca tek bir girdiyi yönetmeye uygundur.</p> <p>Ex: Bir Web günlüğü web sitesi için, Yazılar bir Kaynak Grubu tipinde olur, Ana sayfa tek bir tip olur.</p>",
        "app.components.GuidedTour.CTB.create.cta.title": "Derlem tipi oluştur",
        "app.components.GuidedTour.CTB.create.title": "🧠 İlk derlem tipi yarat",
        "app.components.GuidedTour.CTB.success.content": "<p>İyi gidiyor!</p><b>⚡️ Dünya ile paylaşmak istediğiniz şey nedir?</b>",
        "app.components.GuidedTour.CTB.success.title": "Adım 1: Tamamlanan ✅",
        "app.components.GuidedTour.apiTokens.create.content": "<p>Burada bir kimlik doğrulama belirteci oluşturun ve az önce oluşturduğunuz içeriği alın.</p>",
        "app.components.GuidedTour.apiTokens.create.cta.title": "API Belirteci Oluştur",
        "app.components.GuidedTour.apiTokens.create.title": "🚀 İçeriğe bakın.",
        "app.components.GuidedTour.apiTokens.success.content": "<p>Bir HTTP isteği yaparak eyleme bakın:</p><ul><li><p>Bu URL 'ye: <light>https://' <'YOUR_DOMAIN'> '/api/' <'sizin_CT'> '</light></p></li><li><p>Üstbilgiyle: <light>Yetki:' <'XX_ENCODE_CASE_ONE 'siz_api_token'> '</light></p></p></li><p>İçerikle etkileşimde bulunabilmek için <documentationLink>belgeler</documentationLink>' e bakın.</p>",
        "app.components.GuidedTour.apiTokens.success.cta.title": "Ana sayfaya geri dön",
        "app.components.GuidedTour.apiTokens.success.title": "Adım 3: Tamamlanan ✅",
        "app.components.GuidedTour.create-content": "İçerik yarat",
        "app.components.GuidedTour.home.CM.title": "⚡️ Dünya ile paylaşmak istediğiniz şey nedir?",
        "app.components.GuidedTour.home.CTB.cta.title": "İçerik tipi Oluşturucu 'ya git",
        "app.components.GuidedTour.home.CTB.title": "🧠 İçerik yapısını oluşturun",
        "app.components.GuidedTour.home.apiTokens.cta.title": "API ' yi Sına",
        "app.components.GuidedTour.skip": "Turu atla",
        "app.components.GuidedTour.title": "Başlamak için 3 adım",
        "app.components.HomePage.create": "İlk İçerik tipinizi yaratın",
        "app.components.HomePage.roadmap": "Yol haritamıza bakın",
        "app.components.LeftMenu.collapse": "Gezinme çubuğunu daralt",
        "app.components.LeftMenu.expand": "Gezinme çubuğunu genişlet",
        "app.components.LeftMenu.logout": "Oturumu Kapat",
        "app.components.LeftMenu.navbrand.title": "Strapi Gösterge Panosu",
        "app.components.LeftMenu.navbrand.workplace": "Çalışma Alanı",
        "app.components.LeftMenuLinkContainer.collectionTypes": "Veri Toplama Tipleri",
        "app.components.LeftMenuLinkContainer.singleTypes": "Tek Tipler",
        "app.components.ListPluginsPage.deletePlugin.description": "Eklentiyi kaldırmanız birkaç saniye sürebilir.",
        "app.components.ListPluginsPage.deletePlugin.title": "Kaldırma",
        "app.components.MarketplaceBanner": "Topluluk tarafından oluşturulan eklentileri keşfedin ve projenizi başlatmak için, Strapi Muhteşem 'in üzerinde birçok harika şey keşfedin.",
        "app.components.MarketplaceBanner.image.alt": "bir strapi roket logosu",
        "app.components.MarketplaceBanner.link": "Şimdi kontrol et.",
        "app.components.Onboarding.help.button": "Yardım düğmesi",
        "app.components.ToggleCheckbox.off-label": "Yanlış",
        "app.components.ToggleCheckbox.on-label": "Doğru",
        "app.components.UpgradePlanModal.button": "Ek bilgi",
        "app.components.UpgradePlanModal.limit-reached": "Sınıra ulasdınız.",
        "app.components.UpgradePlanModal.text-ce": "Topluluk Sürümü",
        "app.components.UpgradePlanModal.text-ee": "Enterprise Edition",
        "app.components.UpgradePlanModal.text-power": "Planınızı Enterprise Edition 'a yükselterek, Strapi 'nin tam gücünü açığa çıkarın.",
        "app.components.UpgradePlanModal.text-strapi": "Planınızı şu şekilde büyüterek",
        "app.components.Users.MagicLink.connect": "Bu kullanıcıya erişim vermek için bu bağlantıyı kopyalayın ve paylaşın",
        "app.components.Users.MagicLink.connect.sso": "Bu bağlantıyı kullanıcıya gönder, ilk oturum açma bir SSO sağlayıcısı aracılığıyla yapılabilir",
        "app.components.Users.ModalCreateBody.block-title.details": "Kullanıcı ayrıntıları",
        "app.components.Users.ModalCreateBody.block-title.roles": "Kullanıcının rolleri",
        "app.components.Users.ModalCreateBody.block-title.roles.description": "Bir kullanıcının bir ya da birkaç role sahip olabilir",
        "app.components.Users.SortPicker.button-label": "Sıralama temeli",
        "app.components.Users.SortPicker.sortby.email_asc": "E-posta (A-Z)",
        "app.components.Users.SortPicker.sortby.email_desc": "E-posta (Z ' den A)",
        "app.components.Users.SortPicker.sortby.firstname_asc": "Adı (A 'dan Z' ye)",
        "app.components.Users.SortPicker.sortby.firstname_desc": "Birinci ad (Z 'den A' ya)",
        "app.components.Users.SortPicker.sortby.lastname_asc": "Soyadı (A 'dan Z' ye)",
        "app.components.Users.SortPicker.sortby.lastname_desc": "Soyadı (Z 'den A' ya)",
        "app.components.Users.SortPicker.sortby.username_asc": "Kullanıcı Adı (A-Z)",
        "app.components.Users.SortPicker.sortby.username_desc": "Kullanıcı Adı (Z-A)",
        "app.containers.AuthPage.ForgotPasswordSuccess.text.contact-admin": "Bu bağlantıyı almezseniz, lütfen yöneticinizle iletişim kurun.",
        "app.containers.AuthPage.ForgotPasswordSuccess.text.email": "Parola kurtarma bağlantınızı almak birkaç dakika sürebilir.",
        "app.containers.AuthPage.ForgotPasswordSuccess.title": "Eposta gönderildi",
        "app.containers.Users.EditPage.form.active.label": "Etkin",
        "app.containers.Users.EditPage.header.label": "{ name } Öğesini Düzenle",
        "app.containers.Users.EditPage.header.label-loading": "Kullanıcıyı düzenle",
        "app.containers.Users.EditPage.roles-bloc-title": "Atfli",
        "app.containers.Users.ModalForm.footer.button-success": "Kullanıcıyı davet et",
        "app.page.not.found": "Üzgünüz! Aradığın sayfayı bulamıyoruz gibi görünüyor.",
        "app.static.links.cheatsheet": "CheatSheet",
        "app.utils.add-filter": "Süzgeç ekle",
        "app.utils.close-label": "Kapat",
        "app.utils.duplicate": "Çoğalt",
        "app.utils.edit": "Düzenle",
        "app.utils.errors.file-too-big.message": "Dosya çok büyük",
        "app.utils.filter-value": "Süzgeç değeri",
        "app.utils.filters": "Süzgeçler",
        "app.utils.notify.data-loaded": "{ target } yüklendi",
        "app.utils.publish": "Yayınla",
        "app.utils.select-all": "Tümünü seç",
        "app.utils.select-field": "Alan seç",
        "app.utils.select-filter": "Süzgeç seç",
        "app.utils.unpublish": "Yayından Kaldır",
        "clearLabel": "Temizle",
        "coming.soon": "Bu içerik şu anda yapım aşamasında ve birkaç hafta içinde geri dönecektir!",
        "components.FilterOptions.FILTER_TYPES.$contains": "içerir (büyük/küçük harf duyarlı",
        "components.FilterOptions.FILTER_TYPES.$endsWith": "ile biter",
        "components.FilterOptions.FILTER_TYPES.$eq": ":",
        "components.FilterOptions.FILTER_TYPES.$gt": "bundan büyük",
        "components.FilterOptions.FILTER_TYPES.$gte": "bundan büyük ya da eşit",
        "components.FilterOptions.FILTER_TYPES.$lt": "küçüktür",
        "components.FilterOptions.FILTER_TYPES.$lte": "küçüktür ya da eşittir",
        "components.FilterOptions.FILTER_TYPES.$ne": "bu değil",
        "components.FilterOptions.FILTER_TYPES.$notContains": "içermez (büyük/küçük harf duyarlı)",
        "components.FilterOptions.FILTER_TYPES.$notNull": "boş değerli değil",
        "components.FilterOptions.FILTER_TYPES.$null": "boş değerli",
        "components.FilterOptions.FILTER_TYPES.$startsWith": "şununla başlar",
        "components.Input.error.contain.lowercase": "Parola en az bir küçük harf içermelidir",
        "components.Input.error.contain.number": "Parola en az bir sayı içermelidir",
        "components.Input.error.contain.uppercase": "Parola en az bir büyük harfli karakter içermeli",
        "components.Input.error.validation.lowercase": "Değer küçük harfli bir dizgi olmalıdır",
        "components.NotAllowedInput.text": "Bu alanı görmek için izin yok",
        "components.Search.placeholder": "Ara ...",
        "components.TableHeader.sort": "Sıralama: { label }",
        "components.Wysiwyg.ToggleMode.markdown-mode": "Markdown kipi",
        "components.Wysiwyg.ToggleMode.preview-mode": "Önizleme kipi",
        "components.pagination.go-to": "Şu sayfaya git: { page }",
        "components.pagination.go-to-next": "Sonraki sayfaya git",
        "components.pagination.go-to-previous": "Önceki sayfaya git",
        "components.pagination.remaining-links": "Ve { number } diğer bağlantılar",
        "components.popUpWarning.button.cancel": "Hayır, iptal et",
        "components.popUpWarning.button.confirm": "Evet, doğrula",
        "content-manager.App.schemas.data-loaded": "Şemalar başarıyla yüklendi",
        "content-manager.DynamicTable.relation-loaded": "İlişkiler yüklendi",
        "content-manager.DynamicTable.relation-loading": "İlişkiler yükleniyor",
        "content-manager.DynamicTable.relation-more": "Bu ilişki, görüntülenenden daha fazla varlık içeriyor",
        "content-manager.HeaderLayout.button.label-add-entry": "Yeni girdi oluştur",
        "content-manager.api.id": "API Tanıtıcısı",
        "content-manager.components.DragHandle-label": "Sürükle",
        "content-manager.components.DraggableCard.delete.field": "{ item } Öğesini Sil",
        "content-manager.components.DraggableCard.edit.field": "{ item } Öğesini Düzenle",
        "content-manager.components.DraggableCard.move.field": "{ item } öğesini taşı",
        "content-manager.components.DynamicTable.row-line": "öğe satırı { numara }",
        "content-manager.components.DynamicZone.ComponentPicker-label": "Bir bileşen seç",
        "content-manager.components.DynamicZone.add-component": "{ componentName } bileşenine bir bileşen ekleyin",
        "content-manager.components.DynamicZone.delete-label": "{ name } adını sil",
        "content-manager.components.DynamicZone.error-message": "Bileşende hata (lar) var",
        "content-manager.components.DynamicZone.missing-components": "Orada { number, plural, = 0 { are # eksik bileşenler } bir { is # eksik bileşen } diğer { is # eksik bileşenler } }",
        "content-manager.components.DynamicZone.move-down-label": "Bileşeni aşağı taşı",
        "content-manager.components.DynamicZone.move-up-label": "Bileşeni yukarı taşı",
        "content-manager.components.DynamicZone.pick-compo": "Bir bileşen seç",
        "content-manager.components.DynamicZone.required": "Bileşen gerekli",
        "content-manager.components.FieldItem.linkToComponentLayout": "Bileşenin yerleşim düzenini ayarla",
        "content-manager.components.FieldSelect.label": "Alan ekle",
        "content-manager.components.LeftMenu.Search.label": "İçerik tipi ara",
        "content-manager.components.LeftMenu.collection-types": "Veri Toplama Tipleri",
        "content-manager.components.LeftMenu.single-types": "Tek Tipler",
        "content-manager.components.NotAllowedInput.text": "Bu alanı görmek için izin yok",
        "content-manager.components.RepeatableComponent.error-message": "Bileşen (ler) hata içeriyor",
        "content-manager.components.Select.draft-info-title": "Durum: Taslak",
        "content-manager.components.Select.publish-info-title": "Durum: Yayınlandı",
        "content-manager.components.SettingsViewWrapper.pluginHeader.description.edit-settings": "Düzenleme görünümünün nasıl görüneceğini uyarlayın.",
        "content-manager.components.SettingsViewWrapper.pluginHeader.description.list-settings": "Liste görünümünün ayarlarını tanımlayın.",
        "content-manager.components.SettingsViewWrapper.pluginHeader.title": "Görünümü yapılandır-{ name }",
        "content-manager.components.TableDelete.label": "{ number, plural, one { # entry } other { # entris } } seçili",
        "content-manager.components.empty-repeatable": "Henüz giriş yok. Bir tane eklemek için aşağıdaki düğmeyi tıklatın.",
        "content-manager.components.notification.info.maximum-requirement": "Alan sayısı üst sınırına ulasdınız",
        "content-manager.components.notification.info.minimum-requirement": "Alt sınır gereksinmesine uyan bir alan eklendi",
        "content-manager.components.repeatable.reorder.error": "Bileşeninizin alanı yeniden sıralanırken bir hata oluştu, lütfen yeniden deneyin",
        "content-manager.components.reset-entry": "Girişi sıfırla",
        "content-manager.components.uid.apply": "uygula",
        "content-manager.components.uid.available": "Kullanılabilir",
        "content-manager.components.uid.regenerate": "Yeniden Oluştur",
        "content-manager.components.uid.suggested": "önerilen",
        "content-manager.components.uid.unavailable": "Kullanılamıyor",
        "content-manager.containers.Edit.Link.Layout": "Yerleşim düzenini yapılandır",
        "content-manager.containers.Edit.Link.Model": "Veri toplama tipini düzenle",
        "content-manager.containers.Edit.delete-entry": "Bu girdiyi sil",
        "content-manager.containers.Edit.information": "Bilgi",
        "content-manager.containers.Edit.information.by": "Bu şekilde",
        "content-manager.containers.Edit.information.created": "Oluşturuldu",
        "content-manager.containers.Edit.information.draftVersion": "taslak sürüm",
        "content-manager.containers.Edit.information.editing": "Düzenleme",
        "content-manager.containers.Edit.information.lastUpdate": "Son güncelleme",
        "content-manager.containers.Edit.information.publishedVersion": "yayınlanan sürüm",
        "content-manager.containers.Edit.pluginHeader.title.new": "Girdi oluşturma",
        "content-manager.containers.EditSettingsView.modal-form.edit-field": "Alanı düzenle",
        "content-manager.containers.EditView.add.new-entry": "Girdi ekleme",
        "content-manager.containers.EditView.notification.errors": "Formda bazı hatalar var",
        "content-manager.containers.List.draft": "Taslak",
        "content-manager.containers.List.published": "Yayınlandı",
        "content-manager.containers.ListPage.items": "{ number, plural, = 0 { items } bir { item } other { items } }",
        "content-manager.containers.ListPage.table-headers.published_at": "Durum",
        "content-manager.containers.ListSettingsView.modal-form.edit-label": "{ fieldName } alanını düzenle",
        "content-manager.containers.SettingPage.add.field": "Başka bir alan ekle",
        "content-manager.containers.SettingPage.add.relational-field": "Başka bir ilişkisel alan ekle",
        "content-manager.containers.SettingPage.editSettings.entry.title": "Girdi başlığı",
        "content-manager.containers.SettingPage.editSettings.entry.title.description": "Girişinizin görüntülenen alanını ayarlayın",
        "content-manager.containers.SettingPage.editSettings.relation-field.description": "Görüntülenen alanı hem düzenleme hem de liste görünümlerinde ayarlama",
        "content-manager.containers.SettingPage.layout": "Yerleşim Düzeni",
        "content-manager.containers.SettingPage.listSettings.description": "Bu kaynak grubu tipine ilişkin seçenekleri yapılandırın",
        "content-manager.containers.SettingPage.pluginHeaderDescription": "Bu Kaynak Grubu Tipi için belirli ayarları yapılandır",
        "content-manager.containers.SettingPage.settings": "Ayarlar",
        "content-manager.containers.SettingPage.view": "Görüntüle",
        "content-manager.containers.SettingViewModel.pluginHeader.title": "Content Manager-{ name }",
        "content-manager.containers.SettingsPage.Block.contentType.title": "Veri Toplama Tipleri",
        "content-manager.containers.SettingsPage.Block.generalSettings.description": "Veri Toplama Tipleriniz için varsayılan seçenekleri yapılandırın",
        "content-manager.containers.SettingsPage.pluginHeaderDescription": "Tüm veri toplama tipleriniz ve gruplarınız için ayarları yapılandırın",
        "content-manager.containers.SettingsView.list.subtitle": "Veri toplama tiplerinizin ve gruplarınızın düzenini ve görünümünü yapılandırmanızı sağlar",
        "content-manager.containers.SettingsView.list.title": "Yapılandırmaları görüntüle",
        "content-manager.edit-settings-view.link-to-ctb.components": "Bileşeni düzenle",
        "content-manager.edit-settings-view.link-to-ctb.content-types": "İçerik tipini düzenle",
        "content-manager.emptyAttributes.button": "Derlem tipi oluşturucuya git",
        "content-manager.emptyAttributes.description": "İlk alanınızı Veri Toplama Tipinize ekleyin",
        "content-manager.form.Input.sort.order": "Varsayılan sıralama düzeni",
        "content-manager.form.Input.wysiwyg": "WYSIWYG olarak görüntüle",
        "content-manager.global.displayedFields": "Görüntülenen Alanlar",
        "content-manager.groups": "Gruplar",
        "content-manager.groups.numbered": "Gruplar ({ number })",
        "content-manager.header.name": "İçerik",
        "content-manager.link-to-ctb": "Modeli düzenle",
        "content-manager.models": "Veri Toplama Tipleri",
        "content-manager.models.numbered": "Derlem Tipleri ({ number })",
        "content-manager.notification.info.minimumFields": "En az bir alan görüntülenmeniz gerekir",
        "content-manager.notification.upload.error": "Dosyalarınız karşıya yüklenirken bir hata oluştu",
        "content-manager.pages.ListView.header-subtitle": "{ number, plural, = 0 { # entris } bir { # giriş } diğer { # entris } } bulundu",
        "content-manager.pages.NoContentType.button": "İlk İçeriğinizi yaratın-Tip",
        "content-manager.pages.NoContentType.text": "Henüz herhangi bir içeriğiniz yok, ilk İçerik Tipinizi oluşturmanızı öneririz.",
        "content-manager.permissions.not-allowed.create": "Belge yaratmanıza izin verilmiyor",
        "content-manager.permissions.not-allowed.update": "Bu belgeyi görmenize izin verilmiyor",
        "content-manager.popUpWarning.warning.publish-question": "Yine de yayınlamak istiyor musunuz?",
        "content-manager.popUpWarning.warning.unpublish": "Bu içeriğin yayınlanmasını kaldır,<br></br>otomatik olarak bir taslağın üzerine değiştirir.",
        "content-manager.popUpWarning.warning.unpublish-question": "Yayınlamamak istediğinizden emin misiniz?",
        "content-manager.popUpwarning.warning.has-draft-relations.button-confirm": "Evet, yayınla",
        "content-manager.popUpwarning.warning.has-draft-relations.message": "<b>{ count, plural, = 0 { içerik ilişkilerinizi } bir { içerik ilişkinizin } biri }</b> henüz yayınlanmadı.<br></br>Bozuk bağlantıları ve projenizdeki hataları yürürlüğe soyabilir.",
        "content-manager.popover.display-relations.label": "Görüntü birimi ilişkileri",
        "content-manager.success.record.publish": "Yayınlandı",
        "content-manager.success.record.unpublish": "Yayından kaldırıldı",
        "content-manager.utils.data-loaded": "{ number, plural, = 1 { entry has } other { entry has } } başarıyla yüklendi",
        "content-manager.apiError.This attribute must be unique": "{ field } benzersiz olmalıdır",
        "form.button.continue": "Devam",
        "global.actions": "Eylemler",
        "global.back": "Geri",
        "global.change-password": "Parolayı değiştir",
        "global.content-manager": "İçerik Yöneticisi",
        "global.continue": "Devam",
        "global.delete": "Sil",
        "global.delete-target": "{ target } öğesini sil",
        "global.description": "Açıklama",
        "global.details": "Ayrıntılar",
        "global.disabled": "Devre dışı",
        "global.documentation": "Belgeler",
        "global.enabled": "Etkin",
        "global.finish": "Son",
        "global.marketplace": "Pazar Yeri",
        "global.name": "Ad",
        "global.none": "Yok",
        "global.password": "Parola",
        "global.plugins": "Eklentiler",
        "global.profile": "Profil",
        "global.reset-password": "Parolayı sıfırla",
        "global.roles": "Roller",
        "global.save": "Kaydet",
        "global.see-more": "Daha fazla bilgi",
        "global.select": "Seç",
        "global.select-all-entries": "Tüm girdileri seç",
        "global.settings": "Ayarlar",
        "global.type": "Tip",
        "global.users": "Kullanıcılar",
        "notification.contentType.relations.conflict": "İçerik tipinin çakışan ilişkileri var",
        "notification.default.title": "Bilgi:",
        "notification.link-copied": "Bağlantı panoya kopyalandı",
        "notification.permission.not-allowed-read": "Bu belgeyi görmenize izin verilmiyor",
        "notification.success.delete": "Öğe silindi",
        "notification.success.saved": "Kaydedildi",
        "notification.success.title": "Başarı:",
        "notification.version.update.message": "Strapi 'nin yeni bir sürümü var!",
        "notification.warning.title": "Uyarı:",
        "or": "YA DA",
        "skipToContent": "İçeriğe atla",
        "submit": "Gönder",
        "Analytics": "Analizler",
        "Auth.form.button.forgot-password": "E-posta gönder",
        "Auth.form.button.login": "Giriş",
        "Auth.form.button.register": "Başlamaya hazır",
        "Auth.form.email.label": "E-posta",
        "Auth.form.email.placeholder": "kai@doe.com",
        "Auth.form.error.blocked": "Hesabınız yönetici tarafından engellendi.",
        "Auth.form.error.code.provide": "Geçersiz sağlanmış kod.",
        "Auth.form.error.confirmed": "Tanımladığınız e-posta onaylanmadı.",
        "Auth.form.error.email.invalid": "E-postası geçersiz.",
        "Auth.form.error.email.provide": "Lütfen kullanıcı adınızı veya e-postanızı belirtin.",
        "Auth.form.error.email.taken": "E-posta zaten alınmış",
        "Auth.form.error.invalid": "Kimlik veya şifre geçersiz.",
        "Auth.form.error.params.provide": "Geçersiz sağlanmış kod parametresi.",
        "Auth.form.error.password.format": "Şifreniz `$` sembolünü üç kezden fazla içeremez.",
        "Auth.form.error.password.local": "Bu kullanıcı hiçbir bir şifre belirlemedi; hesap oluşturma sırasında kullanılan sağlayıcı aracılığıyla lütfen giriş yapınız..",
        "Auth.form.error.password.matching": "Parolalar uyuşmuyor.",
        "Auth.form.error.password.provide": "Lütfen şifrenizi girin.",
        "Auth.form.error.ratelimit": "Çok fazla deneme var. Lütfen bir dakika sonra tekrar deneyin.",
        "Auth.form.error.user.not-exist": "Bu e-posta bulunmamaktadır..",
        "Auth.form.error.username.taken": "Kullanıcı adı zaten alınmış",
        "Auth.form.forgot-password.email.label": "E-postanızı giriniz",
        "Auth.form.forgot-password.email.label.success": "E-posta başarıyla gönderildi, ",
        "Auth.form.register.news.label": "Beni gelecekteki özellikler ve geliştirmeler hakkında bilgilendir (bunu seçerek {terms} ve {policy}'leri kabul etmiş sayılırsınız)",
        "Auth.form.rememberMe.label": "Beni hatırla",
        "Auth.form.username.label": "Kullanıcı Adı",
        "Auth.form.username.placeholder": "Kai Doe",
        "Auth.link.forgot-password": "Parolanızı mı unuttunuz ?",
        "Auth.link.ready": "Zaten kayıtlı mısınız?",
        "Auth.privacy-policy-agreement.policy": "gizlilik sözleşmesi",
        "Auth.privacy-policy-agreement.terms": "koşullar",
        "Content Manager": "İçerik Yönetimi",
        "Email": "E-posta",
        "Files Upload": "Dosya yükleme",
        "HomePage.helmet.title": "Anasayfa",
        "HomePage.roadmap": "Yol haritamızı görüntüleyin",
        "HomePage.welcome.congrats": "Tebrikler!",
        "HomePage.welcome.congrats.content": "İlk yönetici olarak giriş yaptınız. Strapi'nin güçlü özelliklerini keşfetmek için,",
        "HomePage.welcome.congrats.content.bold": "ilk İçerik-Tipi'ni yaratmanızı öneriyoruz.",
        "New entry": "Yeni kayıt",
        "Password": "Şifre",
        "Provider": "Sağlayıcı",
        "ResetPasswordToken": "Şifre sıfırlama anahtarı",
        "Role": "Rol",
        "Settings.error": "Hata",
        "Settings.global": "Genel Ayarlar",
        "Settings.webhooks.create": "Webhook oluştur",
        "Settings.webhooks.create.header": "Yeni başlık yarat",
        "Settings.webhooks.created": "Webhook oluşturuldu",
        "Settings.webhooks.events.create": "Oluştur",
        "Settings.webhooks.form.events": "Etkinlikler",
        "Settings.webhooks.form.headers": "Başlıklar",
        "Settings.webhooks.form.url": "Url",
        "Settings.webhooks.key": "Anahtar",
        "Settings.webhooks.list.button.add": "Yeni webhook ekle",
        "Settings.webhooks.list.description": "POST değişiklikleri bildirimi al.",
        "Settings.webhooks.list.empty.description": "İlkini bu listeye ekleyin.",
        "Settings.webhooks.list.empty.link": "Dökümantasyonumuzu görüntüleyin",
        "Settings.webhooks.list.empty.title": "Henüz bir webhook yok",
        "Settings.webhooks.singular": "webhook",
        "Settings.webhooks.title": "Webhooklar",
        "Settings.webhooks.trigger": "Tetikleyici",
        "Settings.webhooks.trigger.cancel": "Tetikleyiciyi iptal et",
        "Settings.webhooks.trigger.pending": "Bekleniyor...",
        "Settings.webhooks.trigger.save": "Lütfen tetikleyiciyi kaydedin",
        "Settings.webhooks.trigger.success": "Başarılı!",
        "Settings.webhooks.trigger.success.label": "Tetikleyici başarılı",
        "Settings.webhooks.trigger.test": "Test-tetikleyici",
        "Settings.webhooks.trigger.title": "Tetikleyiciden önce kaydet",
        "Settings.webhooks.value": "Değer",
        "Username": "Kullanıcı Adı",
        "Users": "Kullanıcılar",
        "Users & Permissions": "Kullanıcılar & İzinler",
        "app.components.BlockLink.code": "Kod örnekleri",
        "app.components.Button.cancel": "İptal",
        "app.components.Button.reset": "Sıfırla",
        "app.components.ComingSoonPage.comingSoon": "Çok Yakında",
        "app.components.DownloadInfo.download": "İndirme devam ediyor...",
        "app.components.DownloadInfo.text": "Bu birkaç dakika sürebilir. Sabrınız için teşekkürler.",
        "app.components.EmptyAttributes.title": "Alan henüz yok",
        "app.components.HomePage.button.blog": "BLOG SAYFASINDA DAHA FAZLASINI GÖRÜN",
        "app.components.HomePage.community": "Topluluğumuza ulaşın",
        "app.components.HomePage.community.content": "Farklı kanallarda takım üyeleri, katkıda bulunanlar ve geliştiricilere ulaşın.",
        "app.components.HomePage.welcome": "Panele hoşgeldiniz.",
        "app.components.HomePage.welcome.again": "Hoşgeldiniz ",
        "app.components.HomePage.welcomeBlock.content": "Sizi topluluk üyelerinden biri olarak görmekten mutluyuz. Sürekli olarak geri bildirim alabilmemiz için bize doğrudan mesaj göndermeye çekinmeyin ",
        "app.components.HomePage.welcomeBlock.content.again": "Projenizde ilerleme kaydedeceğinizi umuyoruz... Strapi ile ilgili en yeni yenilikleri okumaktan çekinmeyin. Ürünü geri bildirimlerinize göre geliştirmek için elimizden geleni yapıyoruz.",
        "app.components.HomePage.welcomeBlock.content.issues": "sorunlar",
        "app.components.HomePage.welcomeBlock.content.raise": " yada yükselt ",
        "app.components.ImgPreview.hint": "Dosyanızı bu alana sürükleyip bırakın ya da bir dosya yüklemek için {browse}",
        "app.components.ImgPreview.hint.browse": "gözat",
        "app.components.InputFile.newFile": "Yeni dosya ekle",
        "app.components.InputFileDetails.open": "Yeni sekmede aç",
        "app.components.InputFileDetails.originalName": "Orjinal isim:",
        "app.components.InputFileDetails.remove": "Bu dosyayı sil",
        "app.components.InputFileDetails.size": "Boyut:",
        "app.components.InstallPluginPage.Download.description": "Eklentiyi indirmek ve yüklemek bir kaç saniye sürebilir.",
        "app.components.InstallPluginPage.Download.title": "İndiriliyor...",
        "app.components.InstallPluginPage.description": "Uygulamanızı rahatlıkla genişletin.",
        "app.components.LeftMenuFooter.help": "Yardım",
        "app.components.LeftMenuFooter.poweredBy": "Gururla sunar ",
        "app.components.LeftMenuLinkContainer.configuration": "Yapılandırma",
        "app.components.LeftMenuLinkContainer.general": "Genel",
        "app.components.LeftMenuLinkContainer.noPluginsInstalled": "Yüklenen eklenti bulunmamaktadır.",
        "app.components.LeftMenuLinkContainer.plugins": "Eklentiler",
        "app.components.ListPluginsPage.description": "Projedeki yüklenen eklentiler.",
        "app.components.ListPluginsPage.helmet.title": "Eklenti Listesi",
        "app.components.Logout.logout": "Çıkış Yap",
        "app.components.Logout.profile": "Profil",
        "app.components.NotFoundPage.back": "Anasayfaya geri dön",
        "app.components.NotFoundPage.description": "Bulunamadı",
        "app.components.Official": "Resmi",
        "app.components.Onboarding.label.completed": "% tamamlandı",
        "app.components.Onboarding.title": "Başlangıç Videolaro",
        "app.components.PluginCard.Button.label.download": "İndir",
        "app.components.PluginCard.Button.label.install": "Zaten yüklenmiş",
        "app.components.PluginCard.PopUpWarning.install.impossible.autoReload.needed": "autoReload özelliği aktif edilmeli. Lütfen uygulamayı `yarn develop` ile başlatın.",
        "app.components.PluginCard.PopUpWarning.install.impossible.confirm": "Anladım!",
        "app.components.PluginCard.PopUpWarning.install.impossible.environment": "Güvenlik nedeniyle bir eklenti yalnızca geliştirme ortamında indirilebilir.",
        "app.components.PluginCard.PopUpWarning.install.impossible.title": "İndirme imkansız",
        "app.components.PluginCard.compatible": "Uygulamanızla uyumlu",
        "app.components.PluginCard.compatibleCommunity": "Toplulukla uyumlu",
        "app.components.PluginCard.more-details": "Daha fazla detay",
        "app.components.listPlugins.button": "Yeni eklenti ekle",
        "app.components.listPlugins.title.none": "Yüklenen eklenti bulunmamaktadır.",
        "app.components.listPluginsPage.deletePlugin.error": "Eklenti kaldırılırken bir hata oluştu",
        "app.containers.App.notification.error.init": "API isteği sırasında bir hata oluştu",
        "app.links.configure-view": "Ekranı düzenle",
        "app.utils.SelectOption.defaultMessage": " ",
        "app.utils.defaultMessage": " ",
        "app.utils.placeholder.defaultMessage": " ",
        "component.Input.error.validation.integer": "Değer sayı olmalı",
        "components.AutoReloadBlocker.description": "Strapi'yi aşağıdaki komutlardan biri ile çalıştırın:",
        "components.AutoReloadBlocker.header": "Bu eklenti için tekrar yükleme özelliği gerekiyor.",
        "components.ErrorBoundary.title": "Bir şeyler yanlış gitti...",
        "components.Input.error.attribute.key.taken": "Bu değer zaten var.",
        "components.Input.error.attribute.sameKeyAndName": "Eşit olamaz",
        "components.Input.error.attribute.taken": "Bu alan ismi zaten var.",
        "components.Input.error.contentTypeName.taken": "Bu isim zaten var.",
        "components.Input.error.custom-error": "{errorMessage} ",
        "components.Input.error.password.noMatch": "Şifreler uyuşmuyor",
        "components.Input.error.validation.email": "Geçersiz e-posta adresi.",
        "components.Input.error.validation.json": "Bu JSON biçimi ile eşleşmiyor",
        "components.Input.error.validation.max": "Değer çok yüksek.",
        "components.Input.error.validation.maxLength": "Değer çok uzun.",
        "components.Input.error.validation.min": "Değer çok az.",
        "components.Input.error.validation.minLength": "Değer çok kısa.",
        "components.Input.error.validation.minSupMax": "Üstü olamaz",
        "components.Input.error.validation.regex": "Regex ile eşleşmiyor.",
        "components.Input.error.validation.required": "Zorunlu alandır.",
        "components.Input.error.validation.unique": "Değer zaten kullanılmış.",
        "components.InputSelect.option.placeholder": "Buradan seçin",
        "components.ListRow.empty": "Gösterilecek veri bulunmamaktadır.",
        "components.OverlayBlocker.description": "Sunucunun yeniden başlatılması gereken bir özellik kullanıyorsunuz. Lütfen sunucu çalışana kadar bekleyin.",
        "components.OverlayBlocker.description.serverError": "Sunucu yeniden başlatılmalı, lütfen terminal üzerinden logları kontrol edin.",
        "components.OverlayBlocker.title": "Yeniden başlatılmayı bekliyor...",
        "components.OverlayBlocker.title.serverError": "Yeniden başlatma beklendiğinden uzun sürüyor",
        "components.PageFooter.select": "sayfa başına kayıt",
        "components.ProductionBlocker.description": "Güvenlik nedeniyle, bu eklentiyi diğer ortamlarda devre dışı bırakmamız gerekir.",
        "components.ProductionBlocker.header": "Bu eklenti yalnızca geliştirme aşamasında mevcuttur.",
        "components.Wysiwyg.collapse": "Daralt",
        "components.Wysiwyg.selectOptions.H1": "H1 başlık",
        "components.Wysiwyg.selectOptions.H2": "H2 başlık",
        "components.Wysiwyg.selectOptions.H3": "H3 başlık",
        "components.Wysiwyg.selectOptions.H4": "H4 başlık",
        "components.Wysiwyg.selectOptions.H5": "H5 başlık",
        "components.Wysiwyg.selectOptions.H6": "H6 başlık",
        "components.Wysiwyg.selectOptions.title": "Başlık ekle",
        "components.WysiwygBottomControls.charactersIndicators": "karakter",
        "components.WysiwygBottomControls.fullscreen": "Genişlet",
        "components.WysiwygBottomControls.uploadFiles": "Dosyanızı bu alana sürükleyip bırakın ya da bir dosya yüklemek için {browse}",
        "components.WysiwygBottomControls.uploadFiles.browse": "Bunları seç",
        "components.popUpWarning.message": "Bunu silmek istediğinizden emin misiniz?",
        "components.popUpWarning.title": "Lütfen onaylayın",
        "content-manager.EditRelations.title": "İlişkili Data",
        "content-manager.components.AddFilterCTA.add": "Filtreler",
        "content-manager.components.AddFilterCTA.hide": "Filtreler",
        "content-manager.components.DraggableAttr.edit": "Düzenlemek için tıklayın",
        "content-manager.components.EmptyAttributesBlock.button": "Ayarlar sayfasına git",
        "content-manager.components.EmptyAttributesBlock.description": "Ayarlarınızı değiştirebilirsiniz",
        "content-manager.components.FilterOptions.button.apply": "Uygula",
        "content-manager.components.FiltersPickWrapper.PluginHeader.actions.apply": "Uygula",
        "content-manager.components.FiltersPickWrapper.PluginHeader.actions.clearAll": "Hepsini temizle",
        "content-manager.components.FiltersPickWrapper.PluginHeader.description": "Filtrelemek için uygulanacak şartları ayarlayın",
        "content-manager.components.FiltersPickWrapper.PluginHeader.title.filter": "Filtreler",
        "content-manager.components.FiltersPickWrapper.hide": "Gizle",
        "content-manager.components.LimitSelect.itemsPerPage": "Sayfa başı",
        "content-manager.components.Search.placeholder": "Kayıt aramak için...",
        "content-manager.components.TableDelete.delete": "Hepsini sil",
        "content-manager.components.TableDelete.deleteSelected": "Silme seçildi",
        "content-manager.components.TableEmpty.withFilters": "Uygulanan filtrelerle {contentType} yoktur...",
        "content-manager.components.TableEmpty.withSearch": "Aramaya karşılık gelen {contentType} yoktur ({search})...",
        "content-manager.components.TableEmpty.withoutFilter": "{contentType} yoktur...",
        "content-manager.containers.Edit.addAnItem": "Bir öğe ekle...",
        "content-manager.containers.Edit.clickToJump": "Kayıta atlamak için tıklayın",
        "content-manager.containers.Edit.delete": "Sil",
        "content-manager.containers.Edit.editing": "Düzenleniyor...",
        "content-manager.containers.Edit.reset": "Reset",
        "content-manager.containers.Edit.returnList": "Listeye dön",
        "content-manager.containers.Edit.seeDetails": "Detaylar",
        "content-manager.containers.Edit.submit": "Kaydet",
        "content-manager.containers.Home.introduction": "Girişlerinizi düzenlemek için soldaki menüdeki ilgili bağlantıya gidin. Bu eklentinin ayarları düzenlemek için uygun bir yol bulunmamaktadır ve halen aktif geliştirme aşamasındadır.",
        "content-manager.containers.Home.pluginHeaderDescription": "Güçlü ve güzel bir arayüz aracılığıyla girişlerinizi yönetin.",
        "content-manager.containers.Home.pluginHeaderTitle": "İçerik Yönetimi",
        "content-manager.containers.List.errorFetchRecords": "Hata",
        "content-manager.containers.ListPage.displayedFields": "Görüntülenen Alanlar",
        "content-manager.containers.SettingPage.attributes": "Nitelik alanları",
        "content-manager.containers.SettingPage.attributes.description": "Niteliklerin sırasını tanımlayın",
        "content-manager.containers.SettingPage.editSettings.description": "Yerleşimi oluşturmak için alanları sürükleyip bırakın",
        "content-manager.containers.SettingPage.editSettings.title": "Düzenle (ayarlar)",
        "content-manager.containers.SettingPage.listSettings.title": "Liste (ayarlar)",
        "content-manager.containers.SettingPage.relations": "İlişkisel alanlar",
        "content-manager.containers.SettingsPage.Block.contentType.description": "Belirli ayarları yapılandırın",
        "content-manager.containers.SettingsPage.Block.generalSettings.title": "Genel",
        "content-manager.emptyAttributes.title": "Henüz bir alan yok",
        "content-manager.error.attribute.key.taken": "Bu değer zaten var.",
        "content-manager.error.attribute.sameKeyAndName": "Eşit olamaz",
        "content-manager.error.attribute.taken": "Bu alan ismi zaten var.",
        "content-manager.error.contentTypeName.taken": "Bu alan ismi zaten var.",
        "content-manager.error.model.fetch": "Modellerin yapılandırması getirilirken bir hata oluştu.",
        "content-manager.error.record.create": "Kayıt oluşturulurken bir hata oluştu.",
        "content-manager.error.record.delete": "Kayıt silinirken bir hata oluştu.",
        "content-manager.error.record.fetch": "Kayıt getirilirken bir hata oluştu.",
        "content-manager.error.record.update": "Kayıt güncelleme sırasında bir hata oluştu.",
        "content-manager.error.records.count": "Sayım kayıtları getirilinceye kadar",
        "content-manager.error.records.fetch": "Kayıtlar getirilirken bir hata oluştu.",
        "content-manager.error.schema.generation": "Şema oluşturma sırasında bir hata oluştu.",
        "content-manager.error.validation.json": "Bu JSON biçimi ile eşleşmiyor",
        "content-manager.error.validation.max": "Değer çok yüksek.",
        "content-manager.error.validation.maxLength": "Değer çok uzun.",
        "content-manager.error.validation.min": "Değer çok az.",
        "content-manager.error.validation.minLength": "Değer çok kısa.",
        "content-manager.error.validation.minSupMax": "Üstü olamaz",
        "content-manager.error.validation.regex": "Regex ile eşleşmiyor.",
        "content-manager.error.validation.required": "Zorunlu alandır.",
        "content-manager.form.Input.bulkActions": "Toplu işlemleri etkinleştir",
        "content-manager.form.Input.defaultSort": "Varsayılan sıralama özelliği",
        "content-manager.form.Input.description": "Açıklama",
        "content-manager.form.Input.description.placeholder": "Profildeki görünen ad",
        "content-manager.form.Input.editable": "Düzenlenebilir alan",
        "content-manager.form.Input.filters": "Filtreleri etkinleştir",
        "content-manager.form.Input.label": "Etiket",
        "content-manager.form.Input.label.inputDescription": "Bu değer, tablonun başında görüntülenen etiketi geçersiz kılar",
        "content-manager.form.Input.pageEntries": "Sayfa başına kayıtlar",
        "content-manager.form.Input.placeholder": "Placeholder",
        "content-manager.form.Input.placeholder.placeholder": "Müthiş değerim",
        "content-manager.form.Input.search": "Aramayı etkinleştir",
        "content-manager.form.Input.search.field": "Bu alanda aramayı etkinleştir",
        "content-manager.form.Input.sort.field": "Bu alana göre sıralamayı etkinleştir",
        "content-manager.notification.error.displayedFields": "En az bir görüntülenen alana ihtiyacınız var",
        "content-manager.notification.error.relationship.fetch": "İlişki getirme sırasında bir hata oluştu.",
        "content-manager.notification.info.SettingPage.disableSort": "Sıralamaya izin verilen tek bir özelliğe sahip olmanız gerekir",
        "content-manager.pageNotFound": "Sayfa bulunamadı",
        "content-manager.plugin.description.long": "Veritabanındaki verileri görmek, düzenlemek ve silmek için hızlı bir yol.",
        "content-manager.plugin.description.short": "Veritabanındaki verileri görmek, düzenlemek ve silmek için hızlı bir yol.",
        "content-manager.popUpWarning.bodyMessage.contentType.delete": "Bu kaydı silmek istediğinizden emin misiniz?",
        "content-manager.popUpWarning.bodyMessage.contentType.delete.all": "Bu kayıtları silmek istediğinizden emin misiniz?",
        "content-manager.popUpWarning.warning.cancelAllSettings": "Değişikliklerinizi iptal etmek istediğinizden emin misiniz?",
        "content-manager.popUpWarning.warning.updateAllSettings": "Bu bütün ayarlarınızı değiştirecektir",
        "content-manager.success.record.delete": "Silindi",
        "content-manager.success.record.save": "Kaydedildi",
        "form.button.done": "Tamam",
        "global.prompt.unsaved": "Bu sayfadan ayrılmak istediğinize emin misiniz? Tüm düzenlemeleriniz kaybolacak",
        "notification.error": "Bir hata oluştu",
        "notification.error.layout": "Düzen alınamadı",
        "notification.form.error.fields": "Form birden fazla hata içeriyor",
        "notification.form.success.fields": "Değişiklikler kaydedildi",
        "request.error.model.unknown": "Bu model bulunmamaktadır.",
        "pages.SettingsPage.toggle.label"  : "Kısıtlı Erişim"
      }
    }
  },
  bootstrap(app) {
    console.log(app);
  },
};
